export const browserComponentUsage = `import { createElement } from "react";
import { pdf } from "@react-pdf/renderer";
import { TextDocument } from "../docn/examples/text-document";
import { registerDocumentFonts } from "../docn/render/fonts";
import { createBrowserAssetResolver } from "../docn/render/assets.browser";
registerDocumentFonts(createBrowserAssetResolver(window.location.origin));
const blob = await pdf(createElement(TextDocument)).toBlob();
const url = URL.createObjectURL(blob);
const link = document.createElement("a");
link.href = url;
link.download = "browser-output.pdf";
link.textContent = "Download browser PDF";
document.body.append(link);
document.getElementById("status")!.textContent = "ready";
window.addEventListener("pagehide", () => URL.revokeObjectURL(url), { once: true });
`;

export const nodeComponentUsage = `import { createElement } from "react";
import { renderToBuffer } from "@react-pdf/renderer";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ComponentDocument } from "../docn/examples/component-document";
import { registerDocumentFonts } from "../docn/render/fonts";
import { createNodeAssetResolver } from "../docn/render/assets.node";
registerDocumentFonts(createNodeAssetResolver(resolve("assets")));
const bytes = await renderToBuffer(createElement(ComponentDocument));
await writeFile("components-output.pdf", bytes);
console.log("component-render-complete", bytes.byteLength);
`;
